[package]
name = "p3-keccak-air"
version = "0.2.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Keccak AIR implementation for Plonky3."

[dependencies]
p3-air = "0.2.0"
p3-field = "0.2.0"
p3-matrix = "0.2.0"
p3-maybe-rayon = "0.2.0"
p3-util = "0.2.0"
tracing = "0.1.37"

[dev-dependencies]
p3-baby-bear = "0.2.0"
p3-koala-bear = "0.2.0"
p3-challenger = "0.2.0"
p3-circle = "0.2.0"
p3-commit = "0.2.0"
p3-dft = "0.2.0"
p3-fri = "0.2.0"
p3-goldilocks = "0.2.0"
p3-blake3 = "0.2.0"
p3-keccak = "0.2.0"
p3-mds = "0.2.0"
p3-merkle-tree = "0.2.0"
p3-mersenne-31 = "0.2.0"
p3-poseidon = "0.2.0"
p3-poseidon2 = "0.2.0"
p3-sha256 = "0.2.0"
p3-symmetric = "0.2.0"
p3-uni-stark = "0.2.0"
rand = "0.8.5"
tracing-subscriber = { version = "0.3.17", features = ["std", "env-filter"] }
tracing-forest = { version = "0.1.6", features = ["ansi", "smallvec"] }

[features]
# TODO: Consider removing, at least when this gets split off into another repository.
# We should be able to enable p3-maybe-rayon/parallel directly; this just doesn't
# seem to work when using cargo with the -p or --package option.
parallel = ["p3-maybe-rayon/parallel"]
asm = ["p3-sha256/asm"]
