[package]
name = "p3-commit"
version = "0.2.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Plonky3 APIs relating to commitments."

[features]
test-utils = ["dep:p3-dft"]

[dependencies]
p3-challenger = "0.2.0"
p3-field = "0.2.0"
p3-matrix = "0.2.0"
p3-util = "0.2.0"

itertools = "0.13.0"
serde = { version = "1.0", default-features = false }

# for testing
p3-dft = { version = "0.2.0", optional = true }

[dev-dependencies]
p3-baby-bear = "0.2.0"
p3-dft = "0.2.0"
rand = "0.8.5"
