[package]
name = "p3-monolith"
version = "0.2.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Plonky3 implementation of the Monolith permutation."

[dependencies]
p3-field = "0.2.0"
p3-goldilocks = "0.2.0"
p3-mersenne-31 = "0.2.0"
p3-mds = "0.2.0"
p3-symmetric = "0.2.0"
generic-array = "1.0"
sha3 = "0.10"

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "permute"
harness = false
