[package]
name = "p3-challenger"
version = "0.3.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
p3-field = { path = "../field", version = "0.3.0" }
p3-util = { path = "../util", version = "0.3.0" }
p3-maybe-rayon = { path = "../maybe-rayon", version = "0.3.0" }
p3-symmetric = { path = "../symmetric", version = "0.3.0" }
tracing = "0.1.37"

[dev-dependencies]
p3-goldilocks = { path = "../goldilocks", version = "0.3.0" }
