[package]
name = "p3-fri"
version = "0.2.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Plonky3 implementation of the FRI protocol."

[dependencies]
p3-challenger = "0.2.0"
p3-commit = "0.2.0"
p3-dft = "0.2.0"
p3-field = "0.2.0"
p3-interpolation = "0.2.0"
p3-matrix = "0.2.0"
p3-maybe-rayon = "0.2.0"
p3-util = "0.2.0"
itertools = "0.13.0"
tracing = "0.1.37"
serde = { version = "1.0", default-features = false, features = ["derive", "alloc"] }

[dev-dependencies]
p3-baby-bear = "0.2.0"
criterion = "0.5.1"
rand = "0.8.5"
rand_chacha = "0.3.1"

[[bench]]
name = "fold_even_odd"
harness = false
