[package]
name = "p3-air"
version = "0.2.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "AIR related APIs for Plonky3."

[dependencies]
p3-field = "0.2.0"
p3-matrix = "0.2.0"

[dev-dependencies]
p3-matrix = "0.2.0"
