[package]
name = "p3-blake3"
version = "0.2.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Blake3 hash wrapper adapted to Plonky3 APIs."

[dependencies]
p3-symmetric = "0.2.0"
blake3 = "1.5"

[features]
neon = ["blake3/neon"]
parallel = ["blake3/rayon"]
