[package]
name = "p3-matrix"
version = "0.2.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Plonky3 Matrix APIs."

[dependencies]
p3-field = "0.2.0"
p3-maybe-rayon = "0.2.0"
p3-util = "0.2.0"
itertools = "0.13.0"
rand = "0.8.5"
serde = { version = "1.0", features = ["derive"] }
transpose = "0.2.3"
tracing = "0.1.37"

[dev-dependencies]
criterion = "0.5.1"
p3-mersenne-31 = "0.2.0"

[[bench]]
name = "transpose_benchmark"
harness = false
