[package]
name = "p3-poseidon"
version = "0.1.5-succinct"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
p3-field = { path = "../field", version = "0.1.5-succinct" }
p3-mds = { path = "../mds", version = "0.1.5-succinct" }
p3-symmetric = { path = "../symmetric", version = "0.1.5-succinct" }
rand = "0.8.5"

[dev-dependencies]
p3-baby-bear = { path = "../baby-bear", version = "0.1.5-succinct" }
p3-goldilocks = { path = "../goldilocks", version = "0.1.5-succinct" }
p3-mersenne-31 = { path = "../mersenne-31", version = "0.1.5-succinct" }
criterion = "0.5.1"

[[bench]]
name = "poseidon"
harness = false
