[package]
name = "p3-poseidon"
version = "0.2.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Plonky3 implementation of the Poseidon permutation."

[dependencies]
p3-field = "0.2.0"
p3-mds = "0.2.0"
p3-symmetric = "0.2.0"
rand = "0.8.5"

[dev-dependencies]
p3-baby-bear = "0.2.0"
p3-goldilocks = "0.2.0"
p3-mersenne-31 = "0.2.0"
criterion = "0.5.1"

[[bench]]
name = "poseidon"
harness = false
