[package]
name = "p3-dft"
version = "0.2.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Discrete Fourier transforms."

[dependencies]
p3-field = "0.2.0"
p3-matrix = "0.2.0"
p3-maybe-rayon = "0.2.0"
p3-util = "0.2.0"
tracing = "0.1.37"
itertools = "0.13.0"

[dev-dependencies]
p3-baby-bear = "0.2.0"
p3-goldilocks = "0.2.0"
p3-mersenne-31 = "0.2.0"
criterion = "0.5.1"
rand = "0.8.5"

[[bench]]
name = "fft"
harness = false
