[package]
name = "p3-util"
version = "0.2.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Utilities used by core Plonky3 code."

[dependencies]
serde = { version = "1.0", default-features = false }
