[package]
name = "p3-uni-stark"
version = "0.2.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Plonky3's end-to-end prover library for basic STARKs."

[dependencies]
p3-air = "0.2.0"
p3-field = "0.2.0"
p3-challenger = "0.2.0"
p3-commit = "0.2.0"
p3-dft = "0.2.0"
p3-matrix = "0.2.0"
p3-maybe-rayon = "0.2.0"
p3-util = "0.2.0"
itertools = "0.13.0"
tracing = "0.1.37"
serde = { version = "1.0", default-features = false, features = ["derive", "alloc"] }

[dev-dependencies]
p3-baby-bear = "0.2.0"
p3-commit = { version = "0.2.0", features = ["test-utils"] }
p3-circle = "0.2.0"
p3-fri = "0.2.0"
p3-keccak = "0.2.0"
p3-mds = "0.2.0"
p3-merkle-tree = "0.2.0"
p3-goldilocks = "0.2.0"
p3-mersenne-31 = "0.2.0"
p3-poseidon2 = "0.2.0"
p3-symmetric = "0.2.0"
rand = "0.8.5"
tracing-subscriber = { version = "0.3.17", features = ["std", "env-filter"] }
tracing-forest = { version = "0.1.6", features = ["ansi", "smallvec"] }
postcard = { version = "1.0.0", default-features = false, features = ["alloc"] }
