[package]
name = "p3-uni-stark"
version = "0.3.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
p3-air = { path = "../air", version = "0.3.0" }
p3-field = { path = "../field", version = "0.3.0" }
p3-challenger = { path = "../challenger", version = "0.3.0" }
p3-commit = { path = "../commit", version = "0.3.0" }
p3-dft = { path = "../dft", version = "0.3.0" }
p3-matrix = { path = "../matrix", version = "0.3.0" }
p3-maybe-rayon = { path = "../maybe-rayon", version = "0.3.0" }
p3-util = { path = "../util", version = "0.3.0" }
itertools = "0.13.0"
tracing = "0.1.37"
serde = { version = "1.0", default-features = false, features = ["derive", "alloc"] }

[dev-dependencies]
p3-baby-bear = { path = "../baby-bear", version = "0.3.0" }
p3-commit = { path = "../commit", features = ["test-utils"], version = "0.3.0" }
p3-circle = { path = "../circle", version = "0.3.0" }
p3-fri = { path = "../fri", version = "0.3.0" }
p3-keccak = { path = "../keccak", version = "0.3.0" }
p3-mds = { path = "../mds", version = "0.3.0" }
p3-merkle-tree = { path = "../merkle-tree", version = "0.3.0" }
p3-mersenne-31 = { path = "../mersenne-31", version = "0.3.0" }
p3-poseidon2 = { path = "../poseidon2", version = "0.3.0" }
p3-symmetric = { path = "../symmetric", version = "0.3.0" }
rand = "0.8.5"
postcard = { version = "1.0.0", default-features = false, features = ["alloc"] }
