[package]
name = "p3-poseidon2"
version = "0.3.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[features]
nightly-features = ["p3-koala-bear/nightly-features", "p3-baby-bear/nightly-features", "p3-mersenne-31/nightly-features", "p3-goldilocks/nightly-features"]

[dependencies]
gcd = "2.3.0"
p3-field = { path = "../field", version = "0.3.0" }
p3-symmetric = { path = "../symmetric", version = "0.3.0" }
p3-mds = { path = "../mds", version = "0.3.0" }
rand = { version = "0.8.5", features = ["min_const_gen"] }

[dev-dependencies]
p3-mersenne-31 = { path = "../mersenne-31", version = "0.3.0" }
p3-baby-bear = { path = "../baby-bear", version = "0.3.0" }
p3-koala-bear = { path = "../koala-bear", version = "0.3.0" }
p3-bn254-fr = { path = "../bn254-fr", version = "0.3.0" }
p3-goldilocks = { path = "../goldilocks", version = "0.3.0" }
criterion = "0.5.1"

[[bench]]
name = "poseidon2"
harness = false