[package]
name = "p3-poseidon2"
version = "0.2.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Plonky3 implementation of the Poseidon2 permutation."

[dependencies]
gcd = "2.3.0"
p3-field = "0.2.0"
p3-symmetric = "0.2.0"
p3-mds = "0.2.0"
rand = { version = "0.8.5", features = ["min_const_gen"] }

[dev-dependencies]
p3-mersenne-31 = "0.2.0"
p3-baby-bear = "0.2.0"
p3-koala-bear = "0.2.0"
p3-bn254-fr = "0.2.0"
p3-goldilocks = "0.2.0"
criterion = "0.5.1"

[[bench]]
name = "poseidon2"
harness = false