[package]
name = "p3-goldilocks"
version = "0.2.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Goldilocks field implementation for Plonky3."

[dependencies]
p3-field = "0.2.0"
p3-dft = "0.2.0"
p3-mds = "0.2.0"
p3-symmetric = "0.2.0"
p3-util = "0.2.0"
p3-poseidon2 = "0.2.0"
num-bigint = { version = "0.4.3", default-features = false }
rand = "0.8.5"
serde = { version = "1.0", default-features = false, features = ["derive"] }

[dev-dependencies]
p3-field-testing = "0.2.0"
rand = { version = "0.8.5", features = ["min_const_gen"] }
criterion = "0.5.1"

[[bench]]
name = "bench_field"
harness = false

[[bench]]
name = "extension"
harness = false
