[package]
name = "p3-symmetric"
version = "0.2.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Plonky3 APIs relating to symmetric cryptography."

[dependencies]
p3-field = "0.2.0"
itertools = "0.13.0"
serde = { version = "1.0", default-features = false, features = ["alloc"] }
