[package]
name = "p3-keccak"
version = "0.2.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Keccak hash wrapper adapted to Plonky3 APIs."

[dependencies]
p3-symmetric = "0.2.0"
tiny-keccak = { version = "2.0.2", features = ["keccak"] }
