[package]
name = "p3-circle"
version = "0.2.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Plonky3 logic relating to the circle group."

[dependencies]
p3-challenger = "0.2.0"
p3-commit = "0.2.0"
p3-dft = "0.2.0"
p3-field = "0.2.0"
p3-fri = "0.2.0"
p3-matrix = "0.2.0"
p3-maybe-rayon = "0.2.0"
p3-util = "0.2.0"

tracing = "0.1.37"
itertools = "0.13.0"
serde = "1"

[dev-dependencies]
p3-baby-bear = "0.2.0"
p3-keccak = "0.2.0"
p3-mds = "0.2.0"
p3-mersenne-31 = "0.2.0"
p3-merkle-tree = "0.2.0"
p3-poseidon = "0.2.0"
p3-symmetric = "0.2.0"

hashbrown = "0.14.3"
rand = "0.8.5"
rand_chacha = "0.3.1"
criterion = "0.5.1"

tracing-subscriber = { version = "0.3.17", features = ["std", "env-filter"] }
tracing-forest = { version = "0.1.6", features = ["ansi", "smallvec"] }

[[bench]]
name = "cfft"
harness = false
