[package]
name = "p3-mersenne-31"
version = "0.2.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Mersenne31 field implementation for Plonky3."

[features]
nightly-features = []

[dependencies]
itertools = "0.13.0"
p3-dft = "0.2.0"
p3-field = "0.2.0"
p3-matrix = "0.2.0"
p3-mds = "0.2.0"
p3-maybe-rayon = "0.2.0"
p3-poseidon2 = "0.2.0"
p3-symmetric = "0.2.0"
p3-util = "0.2.0"
num-bigint = { version = "0.4.3", default-features = false }
rand = "0.8.5"
serde = { version = "1.0", default-features = false, features = ["derive"] }

[dev-dependencies]
criterion = "0.5"
p3-field-testing = "0.2.0"
rand_chacha = "0.3.1"
rand_xoshiro = "0.6.0"

[[bench]]
name = "bench_field"
harness = false

[[bench]]
name = "extension"
harness = false
