name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
    - name: Build
      run: cargo build --verbose --all-targets
    - name: Test
      run: cargo test --verbose

  lints:
    name: Formatting and Clippy
    runs-on: ubuntu-latest
    if: "! contains(toJSON(github.event.commits.*.message), '[skip-ci]')"
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt

      - name: Run cargo fmt
        run: cargo +nightly fmt --all -- --check 
        env:
          CARGO_INCREMENTAL: 1

      - name: Run cargo clippy
        run: cargo +stable clippy --all-features --all-targets -- -D warnings
        env:
          CARGO_INCREMENTAL: 1
